import { 
    Apple, Baby, BadgeCheck, BadgeX, Balloon, BanknoteArrowDown, Bitcoin, 
    BookCheck, BottleWine, Briefcase, Bus, Calculator, Camera, Car, 
    ChartLine, Clapperboard, Coffee, Coins, CreditCard, DollarSign, Droplet, 
    Dumbbell, Flame, Fuel, Gamepad, Gift, GraduationCap, HandCoins, 
    Headphones, HeartPulse, HelpCircle, House, Landmark, Laptop, Map, Music, PiggyBank, 
    Pill, Plane, Receipt, Scissors, Shirt, ShoppingBag, ShoppingCart, 
    Smartphone, Stethoscope, Store, Ticket, Tv, Users, Utensils, Wallet, 
    Wifi, Wrench, Zap 
} from "lucide-react";

export const categoryIcons: Record<string, any> = {
    "apple": Apple,
    "bottle-wine": BottleWine,
    "coffee": Coffee,
    "utensils": Utensils,
    "banknote-arrow-down": BanknoteArrowDown,
    "bitcoin": Bitcoin,
    "calculator": Calculator,
    "chart-line": ChartLine,
    "coins": Coins,
    "credit-card": CreditCard,
    "dollar-sign": DollarSign,
    "hand-coins": HandCoins,
    "landmark": Landmark,
    "piggy-bank": PiggyBank,
    "receipt": Receipt,
    "wallet": Wallet,
    "bus": Bus,
    "car": Car,
    "fuel": Fuel,
    "plane": Plane,
    "droplet": Droplet,
    "flame": Flame,
    "house": House,
    "wifi": Wifi,
    "wrench": Wrench,
    "zap": Zap,
    "shirt": Shirt,
    "shopping-bag": ShoppingBag,
    "shopping-cart": ShoppingCart,
    "store": Store,
    "balloon": Balloon,
    "camera": Camera,
    "clapperboard": Clapperboard,
    "gamepad": Gamepad,
    "headphones": Headphones,
    "helpCircle": HelpCircle,
    "laptop": Laptop,
    "map": Map,
    "music": Music,
    "smartphone": Smartphone,
    "ticket": Ticket,
    "tv": Tv,
    "dumbbell": Dumbbell,
    "heart-pulse": HeartPulse,
    "pill": Pill,
    "scissors": Scissors,
    "stethoscope": Stethoscope,
    "book-check": BookCheck,
    "briefcase": Briefcase,
    "graduation-cap": GraduationCap,
    "baby": Baby,
    "badge-check": BadgeCheck,
    "badge-x": BadgeX,
    "gift": Gift,
    "users": Users
};